"""Generate piece_id -> allowed_squares for the 16 white pieces.

Reachability here means: squares the piece can *legally occupy* at some
point of a legal game (not just moves from the current position).
Pure chess logic, no ROS dependency. Output: config/piece_reachability.yaml.

Rules applied:
- Bishop keeps its square colour for life (c1-bishop = dark, f1-bishop = light).
- Knight graph on 8x8 is connected -> all 64 squares for both knights.
- Rook / queen / king can legally stand on any square over a game.
  Castling is handled separately by move logic and never removes squares.
- White pawns move up (rank+), never backwards, change file only via
  capture (max 7 captures corner-to-corner is legal in theory), and cease
  to exist as pawns on rank 8 (promotion mandatory). En passant creates no
  new square types. -> ranks 2..7, all files, for every pawn.
"""

from __future__ import annotations

from pathlib import Path

import yaml

FILES = "abcdefgh"


def square_color(square: str) -> str:
    """a1 is dark. dark <=> (file_index + rank_index) is even."""
    return "dark" if (FILES.index(square[0]) + int(square[1]) - 1) % 2 == 0 else "light"


def all_squares() -> list[str]:
    return [f"{f}{r}" for r in "12345678" for f in FILES]


def pawn_squares() -> list[str]:
    return [f"{f}{r}" for r in "234567" for f in FILES]


def build() -> dict:
    pieces: dict[str, dict] = {}
    for file_ in FILES:
        pieces[f"white_pawn_{file_}2"] = {
            "type": "pawn",
            "start": f"{file_}2",
            "allowed_squares": pawn_squares(),
        }
    pieces["white_rook_a1"] = {"type": "rook", "start": "a1", "allowed_squares": all_squares()}
    pieces["white_rook_h1"] = {"type": "rook", "start": "h1", "allowed_squares": all_squares()}
    pieces["white_knight_b1"] = {"type": "knight", "start": "b1", "allowed_squares": all_squares()}
    pieces["white_knight_g1"] = {"type": "knight", "start": "g1", "allowed_squares": all_squares()}
    dark = [s for s in all_squares() if square_color(s) == "dark"]
    light = [s for s in all_squares() if square_color(s) == "light"]
    assert len(dark) == 32 and len(light) == 32
    assert square_color("c1") == "dark" and square_color("f1") == "light"
    pieces["white_bishop_c1"] = {"type": "bishop", "start": "c1",
                                 "square_color": "dark", "allowed_squares": dark}
    pieces["white_bishop_f1"] = {"type": "bishop", "start": "f1",
                                 "square_color": "light", "allowed_squares": light}
    pieces["white_queen_d1"] = {"type": "queen", "start": "d1", "allowed_squares": all_squares()}
    pieces["white_king_e1"] = {"type": "king", "start": "e1", "allowed_squares": all_squares()}
    return pieces


def main() -> None:
    pieces = build()
    out = Path(__file__).resolve().parents[1] / "config" / "piece_reachability.yaml"
    total = sum(len(p["allowed_squares"]) for p in pieces.values())
    # Preserve validator-recorded unsafe squares across regenerations.
    unsafe: dict = {}
    if out.is_file():
        try:
            unsafe = yaml.safe_load(out.read_text(encoding="utf-8")).get("unsafe_squares", {}) or {}
        except Exception:
            unsafe = {}
    header = (
        "# piece_id -> squares the piece can legally occupy during a game.\n"
        "# Generated by scripts/generate_reachability.py (pure chess logic).\n"
        "# Geometry validation lives in scripts/validate_routes.py; per-pair\n"
        "# results there join this map with the per-square route geometry.\n"
        "# UNSAFE squares (§8 spec) are recorded here under unsafe_squares\n"
        "# with a reason; they are never silently deleted.\n"
    )
    payload = {"pieces": pieces, "unsafe_squares": unsafe}
    with out.open("w", encoding="utf-8") as stream:
        stream.write(header)
        yaml.safe_dump(payload, stream, sort_keys=False, allow_unicode=True)
    print(f"wrote {out}: {len(pieces)} pieces, {total} allowed pairs")
    for pid, info in pieces.items():
        print(f"  {pid}: {len(info['allowed_squares'])} squares")


if __name__ == "__main__":
    main()
